gallery/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("photos.urls",namespace="photos")),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
        
    

photos/urls.py
from django.urls import path
from . import views

app_name="photos"

urlpatterns = [
    path("search/",views.search_results, name="search_results"),
    path("",views.homepage,name="homepage"),
    
]

photos/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Image(models.Model):
    name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200)
    image=models.ImageField(upload_to='photos/%Y/%m/%d/')
    description=models.TextField(blank=True)
    location=models.ForeignKey("Location",on_delete=models.CASCADE)
    category=models.ManyToManyField("Category")
    

    
    @classmethod
    def search_image(cls,user_input):
        images=cls.objects.filter(category__name__icontains=user_input)
        return images
    
    def __str__(self):
        return self.name
    
        
  
class Location(models.Model):
    name=models.CharField(max_length=50)
     
    def __str__(self):
        return self.name

    
    def save_location(self):
        self.save()

    def delete_location(self):
        self.delete()

class Category(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name

    
    class Meta:
        verbose_name_plural="Category"

    

photos/views.py
from django.shortcuts import render
from .models import Image
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

# Create your views here.
def homepage(request):
    all_images=Image.objects.all()
    paginator=Paginator(all_images,6)
    page=request.GET.get("page")
    
    try:
        all_images=paginator.page(page)

    except PageNotAnInteger:
        all_images=paginator.page(1)
    
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse("")
        all_images=paginator.page(paginator.num_pages)
    if request.is_ajax():
        
        return render(request,"images/list_ajax.html",{"all_images":all_images})   
    return render(request, "homepage.html",{"all_images":all_images})


def search_results(request):
    if "category" in request.GET and request.GET.get("category"):
        search_term=request.GET.get("category")
        found_images=Image.search_image(search_term)
        paginator=Paginator(found_images,6)
        page=request.GET.get("page")

        try:
            found_images=paginator.page(page)

        except PageNotAnInteger:
            found_images=paginator.page(1)

        except EmptyPage:
            if request.is_ajax():
                return HttpResponse("")

            found_images=paginator.page(paginator.num_pages)

        if request.is_ajax():
            return render(request,"images/list_ajax.html",{"all_images":found_images})   

        return render(request,"search_results.html",{"all_images":found_images})

    else:
        message="You havent Searched for any term try again"
        return render(request,"search_results.html",{"message":message})

photos/templates/base.html
{% load static %}



<html>
<head>
  <title> {% block title %} {% endblock title %} </title>
  <link href="https://fonts.googleapis.com/css?family=Raleway:600,900" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="{% static 'styles/styles.css' %}" rel="stylesheet">
<link href="{% static 'styles/navbar.css'%}" rel ="stylesheet">
</head>
<body>
  {% include "navbar.html"%}
  {% block content %}{% endblock content %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script>
    $(document).ready(function() {
      {% block domready %}
      {% endblock %}
    })
  </script>
</body>
</html>

photos/templates/homepage.html
{% extends "base.html"  %}

{% block title %} Homepage {% endblock title%}

{% block content %}

  <div class="gallery-image" >
    {% include "images/list_ajax.html"%}
    
  </div>


  {% endblock content %}


  {% block domready%}
    var page=1;
    var empty_page=false;
    var block_request=false

    $(window).scroll(function(){
      
      var margin=$(document).height()-$(window).height() - 200;
      if($(window).scrollTop() > margin && empty_page==false && block_request==false) {
        
        block_request=true;
        page+=1
        $.get("?page=" + page,function(data){
          console.log('Fetching images')
          $(".gallery-image").append(data);
          if(data=""){
            empty_page=true;
          }
          
          else{
            block_request=false;
        
          }
        })
      }
    });

   

 {% endblock%}

photos/templates/images/list_ajax.html
{% load thumbnail%}
{% for image in all_images%}
    <div class="img-box">
        {%  thumbnail image.image  "300x300" crop="100%" as im %}
      <img src="{{im.url}}" alt="" />
      {% endthumbnail%}
      <div class="transparent-box">
        <div class="caption">
          <p>{{image.location}}</p>
          <p class="opacity-low">{{image.name| truncatewords:10}}</p>
        </div>
      </div> 
    </div>
    
    {% endfor %}

photos/templates/navbar.html
<div class="topnav">
    <a href="">Executive Gallery Store</a>
    <div class="search-container">
      <form action="{% url 'photos:search_results'  %}">
        <input type="text" placeholder="Search.." name="category">
        <button type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>

photos/templates/search_results.html
{% extends "base.html"%}
{% block title %} Search Results {% endblock %}

{% block content%} 

<div class="gallery-image">
    {% include "images/list_ajax.html"%}
</div>
{% endblock %}

{% block domready %}
var page=1;
var empty_page=false
var block_request=false

$(window).scroll(function(){
    var margin=$(document).height()-$(window).height()-200
    if ( $(window).scrollTop()>margin && empty_page==false && block_request==false ){
        block_request=true;
        page+=1;
        $.get("?page=" + page,function(data){
            $(".gallery-image").append(data)

    if(data=""){
        empty_page=true
    }
    else{
        block_request=false
    }
        })

    }
})
{% endblock%}